[Variables]

; --- List Apps (Sidebar List) ---

ListApp1Name=My Computer
ListApp1Path=[::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]
ListApp1Icon=#@#Winicons\Side Icons\Computer.png

ListApp2Name=Documents
ListApp2Path=["C:\Users\%username%\Documents"]
ListApp2Icon=#@#Winicons\Side Icons\Libray Documents.png

ListApp3Name=Pictures
ListApp3Path=["C:\Users\%username%\Pictures"]
ListApp3Icon=#@#Winicons\Side Icons\Folder Pictures.png

ListApp4Name=Music
ListApp4Path=["C:\Users\%username%\Music"]
ListApp4Icon=#@#Winicons\Side Icons\Folder Music.png

ListApp5Name=Downloads
ListApp5Path=["C:\Users\%username%\Downloads"]
ListApp5Icon=#@#Winicons\Side Icons\Folder Downloads.png

ListApp6Name=Videos
ListApp6Path=["C:\Users\%username%\Videos"]
ListApp6Icon=#@#Winicons\Side Icons\Folder Videos.png

ListApp7Name=Trash
ListApp7Path=[::{645FF040-5081-101B-9F08-00AA002F954E}]
ListApp7Icon=#@#Winicons\Side Icons\Trash Empty.png

ListApp8Name=Settings
ListApp8Path=["control.exe" "ncpa.cpl"]
ListApp8Icon=#@#Winicons\Side Icons\Settings.png

ListApp9Name=Control Panel
ListApp9Path=["control.exe"]
ListApp9Icon=#@#Winicons\Side Icons\Control Panel.png

; --- Icon Apps (Bottom Row) ---

IconApp1Name=Word
IconApp1Path=["#@#\Application\Word 2013.lnk"]
IconApp1Icon=#@#\Winicons\Word.png

IconApp2Name=Excel
IconApp2Path=["#@#\Application\Excel 2013.lnk"]
IconApp2Icon=#@#\Winicons\Excel.png

IconApp3Name=Power
IconApp3Path=["#@#\Application\PowerPoint 2013.lnk"]
IconApp3Icon=#@#\Winicons\PowerPoint.png

IconApp4Name=Access
IconApp4Path=["#@#\Application\Access 2013.lnk"]
IconApp4Icon=#@#\Winicons\Access.png
